### ISSUE TITLE
Release v2.0

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#1285]
I would like to release v2.0 around November 15.

(cc'ing @xspec/xspec, @xspec/maven-plugin, @xspec/oxygen-xml-editor-xspec-support, @vincentml)

---

### TODOs

(based on [Release Workflow](https://github.com/xspec/xspec/wiki/Release-Workflow))

1. Prepare the release

   - [x] Release `2.0.6` to Oxygen add-on channel (Stable Release Candidate) (#1282)

   - [x] Notify the XSpec discussion list of the upcoming `v2.0` release.

     - Notable changes
       - [Oxygen add-on changelog](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/master/editors/oxygen/add-on/description/latest.xhtml)
       - CLI-specific changes (#1276 and anything else?)
       - Breaking changes (#1121)

   - [x] Test the add-on `2.0.6` with Oxygen 23
     - All the 4 transformation scenarios should work. (Don't forget to test **Run XSpec Test** with XSLT, XQuery and Schematron.)
     - DITA DTD should take effect via `${xmlCatalogFilesList}` (#980).
     - Loading `xspec.xpr` should disable the add-on and enable its own framework.

   - [x] Draft a new release (`v2.0.7`) at [Releases page](https://github.com/xspec/xspec/releases)
   - [x] Create a pull request incrementing the version (to `2.0.7` without `-SNAPSHOT`) of `pom.xml` and the Oxygen add-on and merge it into `master`

1. Release it

   - [x] Make sure `2.0.7` has been deployed to Maven Central successfully (automated)
   - [x] Publish the release at [Releases page](https://github.com/xspec/xspec/releases)
   - Promote the release `v2.0`
     - [x] XSpec discussion list
     - [x] xml.com
     - [x] xml mailing list
     - [x] tweet

1. Update Wiki
     - [x] Requirements - [Saxon](https://github.com/xspec/xspec/wiki/Requirements#saxon)
     - [x] Running with Maven - [Fetching XSpec file set in Maven](https://github.com/xspec/xspec/wiki/Running-with-Maven#fetching-xspec-file-set-in-maven)

1. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)
   - [x] https://github.com/xspec/xspec/issues/1121#issuecomment-690997853

1. Prepare the next development

   - [x] Close the project and the milestone related to `v2.0`
   - [x] Create the project and the milestone for `v2.1`

1. Start the next development
   - [x] Create a pull request incrementing the version (to `2.1-SNAPSHOT`) of `pom.xml` and merge it into master

   - (If something critical is found, we will create a branch for `2.0.8-SNAPSHOT` and work on it.)

**Comment by cirulls** [comment]
When v2.0 is released, I'd also announced it in https://xspec.io. I can create an article for that based on the release notes and other announcements.

**Comment by AirQuick** [comment]
Thanks @cirulls 
I had been deadly busy lately. I'll have some time from Saturday and will resume working on the release.
Now that Oxygen 23 is there, we'll need to check compatibility with it before releasing v2.0.

**Comment by cirulls** [comment]
No worries @AirQuick, thank you time for the release, you have been doing an amazing job! I'll watch this issue, let me know in case I can be of any help for the release.

**Comment by AirQuick** [comment]
> Draft a new release (`v2.0.7`) at [Releases page](https://github.com/xspec/xspec/releases)

Done. The **Summary** section is written by hand. The rests are auto generated.
Feel free to suggest any improvements.

**Comment by cirulls** [comment]
It looks really good!

**Comment by galtm** [comment]
I agree, it looks really good! Thank you for putting this together, @AirQuick . A couple of minor bits of feedback:

- Consider providing a little context for the heading "Common", such as "Common to Languages Under Test" or "Common to XSLT, XQuery, and Schematron".
- Is #1040 worth mentioning in the summary?

I hadn't noticed #1107 before, but if it's what I think it is, that's a very welcome enhancement and definitely a highlight. :)

**Comment by AirQuick** [comment]
Thanks @galtm 

> * Consider providing a little context for the heading "Common", such as "Common to Languages Under Test" or "Common to XSLT, XQuery, and Schematron".

Renamed the section title "Common to Languages Under Test".

> * Is #1040 worth mentioning in the summary?

Added "Arrays and maps are reported in the same way as XSLT scenarios" to the XQuery section.

> I hadn't noticed #1107 before, but if it's what I think it is, that's a very welcome enhancement and definitely a highlight. :)

#1107 corresponds to "You can write advanced expressions in `@location`" in the draft release note, but it looks somewhat vague. Added "(e.g. `<x:expect-assert location="//sec[@id='lower']" />`)" to it for clarification.

**Comment by AirQuick** [comment]
@cirulls 
If everything looks fine so far, can you possibly own and perform these tasks?

>    - [ ] Publish the release at [Releases page](https://github.com/xspec/xspec/releases)
>    - Promote the release `v2.0`
>      - [ ] XSpec discussion list
>      - [ ] xml.com
>      - [ ] xml mailing list
>      - [ ] tweet

**Comment by cirulls** [comment]
Sure, I'll put aside some time during this weekend to perform these tasks.

**Comment by cirulls** [comment]
Today I did the following:

- [x] Publish the release at [Releases page](https://github.com/xspec/xspec/releases): I hit the release button on https://github.com/xspec/xspec/releases/tag/v2.0.7. I added v2.0.7 in the description (originally it was v2.0), I hope it's fine
- Promote the release `v2.0`
    - [x] XSpec discussion list: see https://groups.google.com/g/xspec-users/c/wYf5XB12A5c  
    - [x] xml.com: see https://www.xml.com/news/2020-11-xspec-v207/ 
    - [x] xml mailing list: see http://lists.xml.org/archives/xml-dev/202011/msg00010.html
    - [ ] tweet: I don't use Twitter but I know @cmarchand and @yamahito do and are very active on Twitter. Would you mind posting a tweet on the XSpec v2.0.7 release?

I also added a post on the xspec.io website, it's on https://xspec.io/posts/xspec_207_release  I added this new promotion step in the [wiki](https://github.com/xspec/xspec/wiki/Release-Workflow/_compare/c9e0a3b2d0b375c4f9e4bee0624e6b0b18a2d2fc).  

@AirQuick: Let me know if I missed something or if there are other outstanding tasks I can help with.

**Comment by AirQuick** [comment]
Thank you @cirulls. They all look prefect!

**Comment by yamahito** [comment]
I did a tweet from Markup UK (and shared it) - should get more exposure that way!

_________________
Tomos Hillman
eXpertML Ltd
+44 7793 242058

**Comment by cirulls** [comment]
At least [one tweet](https://twitter.com/MarkupUKorg/status/1334070525899976705) has gone out. I ticked the boxes related to tweeting. 

@AirQuick: do you think we can close this issue? Any outstanding task for the v2.0.7 release?

**Comment by AirQuick** [comment]
Thanks @yamahito !

Let's close this issue, @cirulls
