### ISSUE TITLE
Release v2.1

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#1398]
I would like to release v2.1 sometime in April.

(cc'ing @xspec/xspec, @xspec/maven-plugin, @xspec/oxygen-xml-editor-xspec-support, @vincentml)

---

### TODOs

(based on [Release Workflow](https://github.com/xspec/xspec/wiki/Release-Workflow))

1. Prepare the release

   - [x] Release `2.1.3` to Oxygen add-on channel (Stable Release Candidate)

   - [x] Notify the XSpec discussion list of the upcoming `v2.1` release.

     - Notable changes
       - [Oxygen add-on changelog](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/master/editors/oxygen/add-on/description/latest.xhtml)

   - [x] Test the add-on `2.1.3` with Oxygen 23.1
     - All the 4 transformation scenarios should work. (Don't forget to test **Run XSpec Test** with XSLT, XQuery and Schematron.)
     - Loading `xspec.xpr` should disable the add-on and enable its own framework.

   - [x] Draft a new release (`v2.1.4`) at [Releases page](https://github.com/xspec/xspec/releases)
   - [x] Create a pull request incrementing the version (to `2.1.4` without `-SNAPSHOT`) of `pom.xml` and the Oxygen add-on and merge it into `master`

1. Release it

   - [x] Make sure `2.1.4` has been deployed to Maven Central successfully (automated)
   - [x] Publish the release at [Releases page](https://github.com/xspec/xspec/releases)
   - Promote the release `v2.1`
     - [x] XSpec discussion list
     - [x] xml.com
     - [x] xml mailing list
     - [x] tweet
     - [x] Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)

1. Update Wiki
   - [x] Complete [the documentation issues](https://github.com/xspec/xspec/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation+milestone%3Av2.1)

1. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)
   - [x] Create it

1. Prepare the next development

   - [x] Close the project and the milestone related to `v2.1`
   - [x] Create the project and the milestone for `v2.2`

1. Start the next development
   - [x] Create a pull request incrementing the version (to `2.2-SNAPSHOT`) of `pom.xml` and merge it into master

   - (If something critical is found, we will create a branch for `2.1.5-SNAPSHOT` and work on it.)

**Comment by cirulls** [comment]
Sound good to me. Feel free to ping me if you want me to help with any of these tasks.

**Comment by cirulls** [comment]
In the promote section I'd add 'Write post on xspec.io' (happy to do that when the time comes).

**Comment by AirQuick** [comment]
> In the promote section I'd add 'Write post on xspec.io' (happy to do that when the time comes).

Good point. Somehow it's slipped through the net. Now I added it.

**Comment by AirQuick** [comment]
> * Draft a new release (`v2.1.4`) at [Releases page](https://github.com/xspec/xspec/releases)

Done. The **Summary** section is written by hand. The rests are auto generated.
Any suggestions for improvement are welcome.

**Comment by galtm** [comment]
> The **Summary** section is written by hand.

Thanks for drafting the release notes! Here are a few editorial suggestions for the summary:

* For the first item, something like "You can mark assertions as pending by setting `@pending` on `x:expect`, as an alternative to using the `x:pending` element." might be clearer to readers who aren't already familiar with the `@pending` attribute. I wasn't sure if it was necessary to say that this new feature complements an existing one, so feel free to remove that part if you think it doesn't add value.
* Under "XSLT", consider shortening the phrase "It is now possible to have different scenarios use" to "Different scenarios can use". But there's nothing wrong with the way you have it, so if you like the emphasis on changing something from impossible to possible, then leave it as is.
* Under "Schematron", "Support" doesn't sound consistent with the other bullets. I think "Supports" would sound better.

**Comment by galtm** [comment]
I scanned through the auto generated part, and I think you've identified the right items to highlight in the summary.

**Comment by AirQuick** [comment]
Thanks @galtm! Reflected your suggestions to the draft release.

**Comment by AirQuick** [comment]
> 4. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)
>    
>    * [x]  Create it

Created: xspec/oXygen-XML-editor-xspec-support#46

> 6. Start the next development
>    
>    * [ ]  Create a pull request incrementing the version (to `2.2-SNAPSHOT`) of `pom.xml` and merge it into master

Created: #1458

**Comment by AirQuick** [comment]
@cirulls
Can you own and perform these tasks in your spare time?

>    * Promote the release `v2.1`
>      
>      * [ ]  XSpec discussion list
>      * [ ]  xml.com
>      * [ ]  xml mailing list
>      * [ ]  tweet
>      * [ ]  Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)

**Comment by cirulls** [comment]
Sure, I'll try to get this done today, I'll keep you posted.

**Comment by cirulls** [comment]
* [x] **XSpec discussion list**: https://groups.google.com/g/xspec-users/c/oyHSVdFgTG0
* [ ] **xml.com**: posted, waiting to be published
* [ ] **xml mailing list**: sent, waiting to be published
* [ ] **Tweet**: I'm not on Twitter but I know @cmarchand and @yamahito are quite active. Would you mind tweeting about the latest XSpec release (v2.1.4)?
* [ ] **Post on xspec.io**: I raised https://github.com/xspec/xspec.github.io/pull/10, if I can get a review for sanity checking I can then merge it and automatically update the website xspec.io.

**Comment by cmarchand** [comment]
Done : https://twitter.com/cmarchand7276/status/1388963939590053888

**Comment by cirulls** [comment]
Thanks @cmarchand ! 

All the promotion tasks have been completed, I had to repost to the xml-dev mailing list as the first message I sent didn't work for some reason. I posted all the links in the comment above.

**Comment by AirQuick** [comment]
Thanks everyone! We're done and I'm closing this issue.
