### ISSUE TITLE
Release v2.2

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#1524]
I would like to release v2.2 sometime in September.

(cc'ing @xspec/xspec, @xspec/maven-plugin, @xspec/oxygen-xml-editor-xspec-support, @vincentml)

---

### TODOs

(based on [Release Workflow](https://github.com/xspec/xspec/wiki/Release-Workflow))

1. Prepare the release

   - [x] Release `2.2.3` to Oxygen add-on channel (Stable Release Candidate)

   - [x] Notify the XSpec discussion list of the upcoming `v2.2` release.

     - Notable changes
       - [Oxygen add-on changelog](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/master/editors/oxygen/add-on/description/latest.xhtml)
       - #1502

   - [x] Test the add-on `2.2.3` with Oxygen 23.1
     - All the 4 transformation scenarios should work. (Don't forget to test **Run XSpec Test** with XSLT, XQuery and Schematron.)
     - Loading `xspec.xpr` should disable the add-on and enable its own framework.

   - [x] Draft a new release (`v2.2.4`) at [Releases page](https://github.com/xspec/xspec/releases)
   - [x] Create a pull request incrementing the version (to `2.2.4` without `-SNAPSHOT`) of `pom.xml` and the Oxygen add-on and merge it into `master`

1. Release it

   - [x] Make sure `2.2.4` has been deployed to Maven Central successfully (automated)
   - [x] Publish the release at [Releases page](https://github.com/xspec/xspec/releases)
   - Promote the release `v2.2`
     - [x] XSpec discussion list
     - [x] xml.com
     - [x] xml mailing list
     - [x] tweet
     - [x] Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)

1. Update Wiki
   - [x] Complete [the documentation issues](https://github.com/xspec/xspec/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation+milestone%3Av2.2)

1. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)
   - [x] Create it

1. Prepare the next development

   - [x] Close the project and the milestone related to `v2.2`
   - [x] Create the project and the milestone for `v2.3`

1. Start the next development
   - [x] Create a pull request incrementing the version (to `2.3-SNAPSHOT`) of `pom.xml` and merge it into master

   - (If something critical is found, we will create a branch for `2.2.5-SNAPSHOT` and work on it.)

**Comment by AirQuick** [comment]
> * Release `2.2.3` to Oxygen add-on channel (Stable Release Candidate)

Opened #1532.

**Comment by cirulls** [comment]
As in the past release, I can help out with the promotion steps but I already know I'm away from computers between 4th and 13th September. I can definitely do something starting from 14th September if need be.

**Comment by AirQuick** [comment]
>    * [x]  Draft a new release (`v2.2.4`) at [Releases page](https://github.com/xspec/xspec/releases)

Done. The **Summary** section is written by hand. The rests are auto generated.
Any suggestions for improvement are welcome.

**Comment by cirulls** [comment]
This looks really good! Feel free to ping me when you get to the promotion steps (if I can help with that part).

**Comment by galtm** [comment]
Sorry for not reviewing it yet; I've been working toward a deadline that's today. I will review the release notes tonight or tomorrow morning.

**Comment by galtm** [comment]
I reviewed the draft of the v2.2.4 section of the Releases page. I agree with @cirulls that it is really good! My only other comment is that "`@location` not pointing to one node throws more helpful error messages." has slightly awkward phrasing. Consider something like "When `@location` does not point to one node, the error message is more helpful."

**Comment by AirQuick** [comment]
Thanks @cirulls and @galtm for reviewing this. I updated the draft with @galtm's suggestion and published it just now.

@cirulls
It would be really appreciated if you could handle the promotion steps.

**Comment by AirQuick** [comment]
> 4. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)

@xspec/oxygen-xml-editor-xspec-support
Done: xspec/oXygen-XML-editor-xspec-support#47

**Comment by cirulls** [comment]
@AirQuick: I'll work on the promotion steps tomorrow, I'll keep you posted when they are done.

**Comment by cirulls** [comment]
Last remaining item to close this ticket is:

>   - [ ] Close the project and the milestone related to `v2.2`

**Comment by AirQuick** [comment]
> GitHub improved GitHub Releases and now provides [auto-generated release notes](https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/#introducing-auto-generated-release-notes). I mention it just in case it could be useful in the future for release notes.

Looks promising. Let's see how it will evolve during the public beta.

**Comment by AirQuick** [comment]
@cirulls @yamahito 
Thank you for making the announcements! I've been busy this month and this release would not have been possible without you.
Now that all the tasks are completed, I'm closing this issue.
