### ISSUE TITLE
Release v3.0

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#1890]
I would like to release v3.0 in mid April 2024.

(cc'ing @xspec/xspec, @xspec/maven-plugin, @xspec/oxygen-xml-editor-xspec-support, @vincentml)

---

### TODOs

(based on [Release Workflow](https://github.com/xspec/xspec/wiki/Release-Workflow))

Tip: Leave time for community feedback between the first notification and the release.

1. Prepare the release

   - [x] Draft a new release (`v3.0`) at [Releases page](https://github.com/xspec/xspec/releases). The draft will help you write the add-on description and the mailing list notification message.

   - [x] Release `3.0` to Oxygen add-on channel (Stable Release Candidate)

   - [x] Test the add-on `3.0` with Oxygen 26.1
     - All the 4 transformation scenarios should work. (Don't forget to test **Run XSpec Test** with XSLT, XQuery and Schematron.)
     - **Schematron Unit Test** and **XQuery Unit Test** templates are available in **File** > **New** dialog, under **Framework templates** > **XSpec**. These aren't the same as the templates under **New Document** in that same dialog.
     - Loading `xspec.xpr` should disable the add-on and enable its own framework.

   - [x] Notify the xml-dev mailing list of the upcoming `v3.0` release. Notable changes are taken from the highlights at the top of the release note draft.

   - [x] Create a pull request incrementing the version (to `3.0` without `-SNAPSHOT`) in `pom.xml` and the Oxygen add-on, and merge it into `master` (UPDATE: it should use a three-part version number, so `3.0.3` instead of `3.0-SNAPSHOT`.)

1. Release it

   - [x] Make sure `3.0` has been deployed to Maven Central successfully (automated)
   - [x] Publish the release at [Releases page](https://github.com/xspec/xspec/releases)
   - Promote the release `v3.0`
     - [x] xml.com
     - [x] xml-dev mailing list
     - [x] tweet (**looking for a volunteer**)
     - [x] Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)

1. Update Wiki
   - [x] Complete [the documentation issues](https://github.com/xspec/xspec/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation+milestone%3Av3.0)
   - [x] Where early drafts of documentation mentioned the "Upcoming" 3.0 release, change the verbiage accordingly.

1. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)
   - [x] Create it

1. Prepare the next development

   - [x] Close the milestone related to `v3.0`
   - [x] Create the milestone for `v3.1`

1. Start the next development
   - [x] Create a pull request incrementing the version (to `3.1-SNAPSHOT`) of `pom.xml` and merge it into master

   - (If something critical is found, we will create a branch for the next `3.0.z-SNAPSHOT` and work on it.)

**Comment by galtm** [comment]
I started drafting Release Notes for v3.0. The list of PRs is not complete yet because some 3.0 PRs are still open, and I will refresh the list before publishing. If I can't get accurate data for Participants in an efficient way, I will remove that column of the tables.

Assuming the draft is visible to you (tell me if it's not), please let me know what you think! Especially the top sections, which are manually authored.
https://github.com/xspec/xspec/releases

Thanks. :)

**Comment by galtm** [comment]
FYI, although #1843 was tagged for the v3.0 milestone, I haven't seen anyone say they are even interested in that change, after I [inquired](https://github.com/xspec/xspec/issues/92#issuecomment-1979506595) in the associated issue. So, I'm inclined to defer it.

**Comment by galtm** [comment]
I am inclined to defer #1786, too, until there is enough time for a proper review. It doesn't seem urgent.

Plan for week of 25 March 2024: After #1897 is merged, I'll update the Oxygen add-on to include the code coverage upgrade. Soon after that, I'll announce the upcoming release, to leave time for community feedback between this notification (this week) and the release (mid April).

**Comment by galtm** [comment]
> * Notify the xml-dev mailing list of the upcoming `v3.0` release.

http://lists.xml.org/archives/xml-dev/202403/msg00003.html

**Comment by galtm** [comment]
> I started drafting Release Notes for v3.0. The list of PRs is not complete yet because some 3.0 PRs are still open, and I will refresh the list before publishing. If I can't get accurate data for Participants in an efficient way, I will remove that column of the tables.
> 
> Assuming the draft is visible to you (tell me if it's not), please let me know what you think! Especially the top sections, which are manually authored. https://github.com/xspec/xspec/releases
> 
> Thanks. :)

Finished drafting the Release Notes.

I filled in **Participants** manually for the tables that are visible by default, by looking at the PR pages. Sometimes, I also remembered that someone contributed to an issue that motivated the PR. This process would have taken a lot of time for tables that are collapsed by default. So, the compromise I used was to give credit in a general way to @AirQuick and @cmarchand for contributing to PRs in some of those collapsed tables.

Feedback is welcome!

**Comment by galtm** [comment]
> * Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)

Draft PR is https://github.com/xspec/xspec.github.io/pull/16 .

**Comment by galtm** [comment]
> * Create a pull request incrementing the version (to `3.0` without `-SNAPSHOT`) in `pom.xml` and the Oxygen add-on, and merge it into `master`

https://github.com/xspec/xspec/pull/1904

**Comment by galtm** [comment]
> * xml-dev mailing list

http://lists.xml.org/archives/xml-dev/202404/msg00004.html

**Comment by galtm** [comment]
> * xml.com

https://www.xml.com/news/2024-04-xspec-v303/

**Comment by galtm** [comment]
> * tweet (**looking for a volunteer**)

@cmarchand , can you post a tweet about XSpec v3.0.3 when you get a chance (if you haven't already)? Thanks!

**Comment by galtm** [comment]
> * Create a pull request incrementing the version (to `3.1-SNAPSHOT`) of `pom.xml` and merge it into master

https://github.com/xspec/xspec/pull/1911 (not merged yet)

**Comment by galtm** [comment]
> 4\. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)

I did as much as I can, given my limited knowledge.
https://github.com/xspec/oXygen-XML-editor-xspec-support/pull/56

If someone else wants to pitch in, please feel free to do so!

**Comment by galtm** [comment]
Thanks, @cmarchand !

**Comment by galtm** [comment]
> > * Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)
> 
> PR is [xspec/xspec.github.io#16](https://github.com/xspec/xspec.github.io/pull/16) .

Merged. The new post about v3.0.3 is live on the xspec.io site. Thanks to @cirulls for the code review!

**Comment by galtm** [comment]
We are done releasing v3.0.3. Thanks to all who contributed code, code reviews, bug reports, discussion points, release announcements, or anything else that helped make v3.0.3 what it is! 🌷
