### ISSUE TITLE
Release v3.1

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#1912]
_Setting up the v3.1 release checklist while clarification ideas are on my mind from the v3.0 release._

**Tip**: Leave time for community feedback between the first notification (Step 1) and the release (Step 2).

**Three-part version numbers**: In this checklist, _num_ means the third part of a three-part version number. Be sure to replace _num_ with whatever the third part should be, which depends on how many intermediate releases were made to capture a "notable change" as described in the release workflow. 

### TODOs

(based on [Release Workflow](https://github.com/xspec/xspec/wiki/Release-Workflow))

1. Prepare the release

   - [x] Draft a new release (`v3.1.num`) at [Releases page](https://github.com/xspec/xspec/releases). The draft will help you write the add-on description and the mailing list notification message. The heading and proposed Git tag should use a three-part version number.

   - [x] Release `3.1.num` to Oxygen add-on channel (Stable Release Candidate)

   - [x] Test the add-on `3.1.num` with Oxygen 26.1
     - All the 4 transformation scenarios should work. (Don't forget to test **Run XSpec Test** with XSLT, XQuery and Schematron.)
     - **Schematron Unit Test** and **XQuery Unit Test** templates are available in **File** > **New** dialog, under **Framework templates** > **XSpec**. These aren't the same as the templates under **New Document** in that same dialog.
     - Loading `xspec.xpr` should disable the add-on and enable its own framework.

   - [x] Notify the xml-dev mailing list (`xml-dev@lists.xml.org`) of the upcoming `v3.1.num` release. Notable changes are taken from the highlights at the top of the release note draft.

1. Release it

   - [x] Create a pull request replacing `-SNAPSHOT` with the number, _num_, in `pom.xml` and the Oxygen add-on. Merge it into `master` 
   - [x] Make sure `3.1.num` has been deployed to Maven Central successfully (automated)
   - [x] Publish the release at [Releases page](https://github.com/xspec/xspec/releases)
   - Promote the release `v3.1.num`
     - [x] xml.com, using form at https://www.xml.com/news/submit-news-item/
     - [x] xml-dev mailing list, `xml-dev@lists.xml.org` [xml-dev list does not work; using `xsl-list@lists.mulberrytech.com` instead this time, because biggest change is for XSLT code coverage]
     - [x] Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)
     - [x] Add comment to #2006 

1. Update Wiki
   - [x] Complete [the documentation issues](https://github.com/xspec/xspec/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation+milestone%3Av3.1)
   - [x] Where early drafts of documentation mentioned the "Upcoming" 3.1 release, change the verbiage accordingly.

1. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)
   - [x] Create it

1. Prepare the next development

   - [x] Close the milestone related to `v3.1`
   - [x] Create the milestone for `v3.2` (or `v4.0` if anticipating a major release)

1. Start the next development
   - [x] Create a pull request incrementing the version (to `3.2-SNAPSHOT` or `4.0-SNAPSHOT` depending on anticipated next release) of `pom.xml` and merge it into master. This step uses a two-part version number, not a three-part version number.

(If something critical is found, we will create a branch for the next `3.1.z-SNAPSHOT` and work on it.)

**Comment by galtm** [comment]
@xspec/xspec, @cmarchand , and @birdya22 : I wrote the first draft of the [v3.1 release notes](https://github.com/xspec/xspec/releases). Can you please take a look and provide feedback, preferably by Aug. 31? Thanks!

I still need to check that the Authors/Participants listings are accurate; I took a quick first stab, but the process is not fully automated and I'm out of time for today. The list of Participants is supposed to include anyone who provided comments or code reviews for a pull request. @birdya22 , when I shepherded your code through GitHub, my aim was to list you as Author. If I also tweaked something in the same pull request, then I listed both of us as authors.

If I left out a name somewhere, it's probably a simple oversight on my part. Feel free to point out mistakes, or you can wait until I do a second pass tomorrow.

**Comment by galtm** [comment]
> or you can wait until I do a second pass tomorrow.

Done with second pass on list of authors and participants.

**Comment by birdya22** [comment]
Looks ok to me.

**Comment by cmarchand** [comment]
Looks good to me too, sorry for the delay.

**Comment by galtm** [comment]
Thanks for your reviews, @birdya22 and @cmarchand ! I'm merging the last two dependency updates and then I will set up the Oxygen add-on for v3.1.1. If I can announce that on the xml-dev list this week, there will be time for users to try out the prerelease before the real release.

**Comment by galtm** [comment]
I finished the dependency updates, including BaseX 11.2 (released a couple of weeks ago, but I only realized that today), and released the add-on for v3.1.1. I'll plan to make the xml-dev announcement at the end of the day on Sep. 5.

**Comment by galtm** [comment]
I added the newest PRs to the release notes, and added a brief mention of "unknown" status to the wiki page, https://github.com/xspec/xspec/wiki/Code-Coverage .

**Comment by galtm** [comment]
After I sent the prerelease announcement email to xml-dev@lists.xml.org today, I received an autoreply that said the list was migrating to a new platform and would be unavailable starting in March 2024. The message had a link to https://groups.oasis-open.org/communities/mycommunities . The site doesn't list xml-dev among the supported lists at https://groups.oasis-open.org/communities/allcommunities. And yet I came across this post from 2 days ago https://groups.oasis-open.org/discussion/ann-release-of-xmlmind-xml-editor-v109#bm59f01d2f-7c07-4611-8301-3f1e465429fd that I didn't receive by email. Meanwhile, the archive at http://lists.xml.org/archives/xml-dev/ goes through July 2024 and no further.

I'll see if I can find out more in the next few days. If xml-dev doesn't work out, a possible fallback is to use xml.com for the prerelease announcement as well as the final release announcement.

If you have information about the xml-dev list or another idea to suggest, please let me know!  : )

**Comment by galtm** [comment]
> If xml-dev doesn't work out, a possible fallback is to use xml.com for the prerelease announcement as well as the final release announcement.

Another possible fallback for the v3.1 prerelease announcement is the xsl-list@lists.mulberrytech.com mailing list (info at https://www.mulberrytech.com/xsl/xsl-list/index.html ). While that might miss some people who use XQuery or Schematron but not XSLT, I think the most important benefit of v3.1 over v3.0 is the set of bug fixes in XSLT code coverage reporting.

**Comment by galtm** [comment]
Another possible fallback for the prerelease announcement: xmlcom.slack.com

**Comment by galtm** [comment]
> * Create a pull request replacing `-SNAPSHOT` with the number, _num_, in `pom.xml` and the Oxygen add-on. Merge it into `master`

Created #2012

**Comment by galtm** [comment]
I updated the draft release notes to reflect:

- The last few pull requests that were merged, and also #2012 that will be merged when ready
- v3.1.2 instead of v3.1.1, in the heading, paragraph text, Git tag to create upon publishing the release, and Git tag that is part of the link to the complete list of PRs (at the end of the release notes)

**Comment by galtm** [comment]
> 3\. Update Wiki

No op because nothing needed to be updated

**Comment by galtm** [comment]
> * Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)

The PR is https://github.com/xspec/xspec.github.io/pull/17

**Comment by galtm** [comment]
I updated the GitHub repos I own to XSpec v3.1.2 and the upgrade worked fine.

Promotion
- https://www.biglist.com/lists/lists.mulberrytech.com/xsl-list/archives/202409/msg00016.html
- https://www.xml.com/news/2024-09-xspec-v312/
- https://xspec.io/posts/xspec_312_release/
- https://github.com/xspec/xspec/issues/2006#issuecomment-2384300380

**Comment by galtm** [comment]
> 4\. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)

I did as much as I know how to do:
https://github.com/xspec/oXygen-XML-editor-xspec-support/pull/57

(BTW, the v3.0.3 draft pull request, https://github.com/xspec/oXygen-XML-editor-xspec-support/pull/56, is still open.)

**Comment by galtm** [comment]
> * Create a pull request incrementing the version (to `3.2-SNAPSHOT` or `4.0-SNAPSHOT` depending on anticipated next release) of `pom.xml`

Created #2015

**Comment by galtm** [comment]
> > * Create a pull request incrementing the version (to `3.2-SNAPSHOT` or `4.0-SNAPSHOT` depending on anticipated next release) of `pom.xml`
> 
> Created #2015

The PR above is done. With that, Release v3.1 is also done! 🍰 

Thanks to everyone who contributed to v3.1 and helped get it out the door, especially @cmarchand and @birdya22!
