### ISSUE TITLE
Release v3.2

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#2017]
**Tip**: Leave time for community feedback between the first notification (Step 1) and the release (Step 2).

**Three-part version numbers**: In this checklist, _num_ means the third part of a three-part version number. Be sure to replace _num_ with whatever the third part should be, which depends on how many intermediate releases were made to capture a "notable change" as described in the release workflow. 

### TODOs

(based on [Release Workflow](https://github.com/xspec/xspec/wiki/Release-Workflow))

1. Prepare the release

   - [x] Draft a new release (`v3.2.num`) at [Releases page](https://github.com/xspec/xspec/releases). The draft will help you write the add-on description and the notification message. The heading and proposed Git tag should use a three-part version number.

   - [x] Release `3.2.num` to Oxygen add-on channel (Stable Release Candidate)

   - [x] Test the add-on `3.2.num` with latest Oxygen
     - All the 4 transformation scenarios should work. (Don't forget to test **Run XSpec Test** with XSLT, XQuery and Schematron.)
     - **Schematron Unit Test** and **XQuery Unit Test** templates are available in **File** > **New** dialog, under **Framework templates** > **XSpec**. These aren't the same as the templates under **New Document** in that same dialog.
     - Loading `xspec.xpr` should disable the add-on and enable its own framework.

   - [x] Notify xmlcom.slack.com of the upcoming `v3.2.num` release. Notable changes are taken from the highlights at the top of the release note draft.

1. Release it

   - [x] Create a pull request replacing `-SNAPSHOT` with the number, _num_, in `pom.xml`. Also use `3.2.num` in `VERSION` (no trailing line break!), `xspec.xpr`, and the Oxygen add-on. Merge it into `master`.
   - [x] Make sure `3.2.num` has been deployed to Maven Central successfully (automated)
   - [x] Update release notes with any PR listings since the pre-release
   - [x] Publish the release at [Releases page](https://github.com/xspec/xspec/releases)
   - Promote the release `v3.2.num`
     - [x] xml.com, using form at https://www.xml.com/news/submit-news-item/
     - [x] xmlcom.slack.com
     - [x] Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)
     - [x] Add comment to #2006 

1. Update Wiki
   - [x] Complete [the documentation issues](https://github.com/xspec/xspec/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation+milestone%3Av3.2)
   - [x] Where early drafts of documentation mentioned the "Upcoming" 3.2 release, change the verbiage accordingly.

1. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)
   - [x] Create it

1. Prepare the next development

   - [x] Close the milestone related to `v3.2`
   - [x] Create the milestone for `v3.3` (or `v4.0` if anticipating a major release)

1. Start the next development
   - [x] Create a pull request incrementing the version (to `3.3-SNAPSHOT` or `4.0-SNAPSHOT` depending on anticipated next release) of `pom.xml` and merge it into master. This step uses a two-part version number, not a three-part version number.

(If something critical is found, we will create a branch for the next `3.2.z-SNAPSHOT` and work on it.)

**Comment by galtm** [comment]
>   [ ]  Draft a new release (`v3.2.num`) at [Releases page](https://github.com/xspec/xspec/releases). The draft will help you write the add-on description and the notification message. The heading and proposed Git tag should use a three-part version number.

@cmarchand , @birdya22 , @xspec/xspec : Please let me know what you think of the draft v3.2 release notes, which you should be able to see at the top of https://github.com/xspec/xspec/releases (when you are logged into GitHub). Preferably by March 9.

The list of Participants is supposed to include anyone who provided comments or code reviews for a pull request. It is not automated. @birdya22 , when I shepherded your code through GitHub, my aim was to list you as Author. If I contributed something else in the same pull request, then I listed both of us as authors. In those cases, the Author column was not automated. The PR, Scope, and Subject columns are automated.

If I left out a name somewhere, it's probably a simple oversight on my part. If you notice any mistakes, please point them out so I can correct them.

**Comment by birdya22** [comment]
I'm a bit confused about Release 3.1.3 and this one, mainly because 3.1.3 contains a number of changes which are also in this release, although generally they are not mentioned in the 3.1.3 Release note. SchXslt 1.10.1 is mentioned in both Release notes.

 I see that #2085, 'fix(report): avoid visible borders on headings', is included in the milestone but is still open and not in the Release note. Are you intending to commit the change and update the Release note before the release happens?

What are your thoughts on supporting Saxon 2.6, which looks as though it will be out quite soon?

**Comment by galtm** [comment]
> I'm a bit confused about Release 3.1.3 and this one, mainly because 3.1.3 contains a number of changes which are also in this release, although generally they are not mentioned in the 3.1.3 Release note. SchXslt 1.10.1 is mentioned in both Release notes.

Good point. v3.1.3 was a tiny "patch" release intended to make one particular bug fix available to a repo that depends on this one. The release of v3.1.3 (#2031) had a more lightweight process, which meant minimal announcement and abbreviated Release Notes. The different nature of the v3.1.3 release compared to the v3.1.2 release is making this v3.2 task more challenging.

Maybe the simplest thing to do is to relabel the list of PRs as something like "Merged Pull Requests since v3.1.2" because that's what it is. The bulleted item about SchXslt 1.10.1 should be either removed or annotated with something like "(also in v3.1.3)". My preference would be to remove the item.

> I see that [#2085](https://github.com/xspec/xspec/pull/2085), 'fix(report): avoid visible borders on headings', is included in the milestone but is still open and not in the Release note. Are you intending to commit the change and update the Release note before the release happens?

Yes. In addition to the PR you mentioned, we sometimes get "dependabot" pull requests for updating dependencies after announcing the release candidate but before the release date. I will update the Release Notes before the actual release, to make sure it lists all merged pull requests.
 
> What are your thoughts on supporting Saxon 2.6, which looks as though it will be out quite soon?

The XSpec release process includes about a 2-week period to allow users to provide feedback or report bugs. As far as Saxon 12.6 goes, I see three possibilities:

A) Suppose Saxon 12.6 isn't released by the time we're ready to release XSpec v3.2 in a few weeks. In this case, I would rather not hold up the XSpec release just for Saxon 12.6.

B) Suppose Saxon 12.6 is released before we release XSpec v3.2, and we begin assessing it. Suppose we quickly find that it's a no-brainer to recommend 12.6 over 12.4 for code coverage and 12.6 doesn't introduce any new incompatibilities with the rest of the XSpec code base. In this case, I'm OK with a small delay in the XSpec release date to give us time to react to 12.6.

C) Suppose Saxon 12.6 is released before we release XSpec v3.2, but it's not the no-brainer as in case (B). Maybe we'd release v3.2 and plan for a potential patch release afterward, to ensure compatibility between Saxon 12.6 and XSpec -- say, v3.2.3 following the main release v3.2.2, which would have followed the release candidate v3.2.1.

These are my thoughts right now, and I'm open to other perspectives.

**Comment by galtm** [comment]
> * [ ]  Create a pull request replacing `-SNAPSHOT` with the number, _num_, in `pom.xml`. Also use `3.2.num` in `VERSION` (no trailing line break!), `xspec.xpr`, and the Oxygen add-on. Merge it into `master`.

Prepared #2091.

**Comment by galtm** [comment]
> Maybe the simplest thing to do is to relabel the list of PRs as something like "Merged Pull Requests since v3.1.2" because that's what it is. The bulleted item about SchXslt 1.10.1 should be either removed or annotated with something like "(also in v3.1.3)". My preference would be to remove the item.

Added "since v3.1.2" and removed SchXslt 1.10.1 item. I also regenerated the content to include the most recently merged PRs and the anticipated merging of #2091 (between now and when the release notes get published).

**Comment by galtm** [comment]
> * Make sure `3.2.num` has been deployed to Maven Central successfully (automated)

I see the 3.2.2 listing at https://central.sonatype.com/artifact/io.xspec/xspec/versions and the page for it at https://central.sonatype.com/artifact/io.xspec/xspec/3.2.2

**Comment by galtm** [comment]
> * Write post on [`xspec.io`](https://github.com/xspec/xspec.github.io)

https://github.com/xspec/xspec.github.io/pull/22

**Comment by galtm** [comment]
> * xml.com, using form at https://www.xml.com/news/submit-news-item/

https://www.xml.com/news/2025-03-xspec-v322/

**Comment by galtm** [comment]
Oxygen 27.1 was released on March 24, 2025, the same day as XSpec v3.2.2. I installed the v3.2.2 add-on in Oxygen 27.1 using the URL https://github.com/xspec/xspec/raw/master/oxygen-addon.xml and it works fine.

I also updated the [Running with Oxygen](https://github.com/xspec/xspec/wiki/Running-with-Oxygen) wiki topic to change https://github.com/xspec/xspec/raw/master/oxygen-addon.xml to https://xspec.io/editors/oxygen/oxygen-addon.xml as the place to get the add-on. From there, it also works fine in Oxygen 27.1.

**Comment by galtm** [comment]
> * Complete [the documentation issues](https://github.com/xspec/xspec/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation+milestone%3Av3.2)

Done; see https://github.com/xspec/xspec/pull/2055#issuecomment-2751253334

**Comment by galtm** [comment]
> 4\. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)

https://github.com/xspec/oXygen-XML-editor-xspec-support/pull/58

**Comment by galtm** [comment]
> * Create a pull request incrementing the version (to `3.3-SNAPSHOT` or `4.0-SNAPSHOT` depending on anticipated next release) of `pom.xml` and merge it into master. This step uses a two-part version number, not a three-part version number.

Created https://github.com/xspec/xspec/pull/2095

**Comment by galtm** [comment]
Now that #2095 is merged, we're officially done with v3.2. Thanks to everyone who helped with v3.2! Especially @cmarchand and @birdya22 -- you have been great collaborators! :rose:

**Comment by cmarchand** [comment]
You do all the job and you say we are great ???

Thanks to you for all the time you give to this project, it's a massive investment !
