### ISSUE TITLE
Release v3.1.3

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#2031]
To make the fix in #2027 available to xspec/xspec-maven-plugin-1 and potentially other users of XSpec via .zip or .jar file, we will release v3.1.3. This release has a small number of commits and will use an abbreviated release process. The checklist below is a subset of the one we will use for v3.2 in the future.

---

**Three-part version numbers**: In this checklist, _num_ means the third part of a three-part version number. Be sure to replace _num_ with whatever the third part should be, which depends on how many intermediate releases were made to capture a "notable change" as described in the release workflow. 

### TODOs

(based on [Release Workflow](https://github.com/xspec/xspec/wiki/Release-Workflow) but abbreviated)

1. Prepare the release

   - [x] From local `master` branch, create a new `v3.1.3-release` branch. Push it upstream to create a `v3.1.3-release` remote branch.

   - [x] Draft a new release (`v3.1.3`) at [Releases page](https://github.com/xspec/xspec/releases). The draft will help you write the add-on description. The heading and proposed Git tag should use a three-part version number.

   - [x] Release `3.1.3` to Oxygen add-on channel on the `v3.1.3-release` remote branch.

   - [x] Test the add-on `3.1.3` with latest Oxygen
     - All the 4 transformation scenarios should work. (Don't forget to test **Run XSpec Test** with XSLT, XQuery and Schematron.)
     - **Schematron Unit Test** and **XQuery Unit Test** templates are available in **File** > **New** dialog, under **Framework templates** > **XSpec**. These aren't the same as the templates under **New Document** in that same dialog.
     - Loading `xspec.xpr` should disable the add-on and enable its own framework.

1. Release it

   - [x] Create a pull request using version `3.1.3` instead of `3.1.3-SNAPSHOT` in `pom.xml`. Merge it into `v3.1.3-release` remote branch.
   - [x] Make sure `3.1.3` has been deployed to Maven Central successfully (automated)
   - [x] Publish the release at [Releases page](https://github.com/xspec/xspec/releases)
   - Promote the release `v3.1.3` minimally
     - [x] Add comment to #2006 

1. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)
   - [ ] <s>Create it</s>

1. Continue with the next development

   - [x] Push the v3.1.3 Oxygen add-on commit to the `master` branch for `v3.2`

(If something critical is found, we will create a branch for the next `3.1.4-SNAPSHOT` and work on it.)

**Comment by galtm** [comment]
@cmarchand , can you please review the short v3.1.3 blurb that I added at https://github.com/xspec/xspec/releases/ ? I didn't create subsections or the table. I'm trying to keep the process as simple as possible, so that a time-consuming process doesn't create disincentives for us to release bug fixes quickly.

I'd also like your code review of #2032 and #2033. Thanks!

**Comment by galtm** [comment]
Thanks for your timely code reviews! I'll merge #2032 now and check back on the other one a little later in the day.

Best,
Amanda

**Comment by galtm** [comment]
Possible workflow changes to consider for the next time we have to do a bug-fix release:

1. Name the branch something like `v3.1.z-release` instead of `v3.1.3-release` so that the branch can be used for v3.1.3, v3.1.4, v3.1.5, etc. if needed. (If we have only one bug-fix release, it doesn't really matter.)
1. Do the Oxygen add-on on the `master` branch and then create the bug-fix branch from there. That way, the Oxygen add-on doesn't have to be on two branches.

**Comment by galtm** [comment]
The Maven deployment succeeded. [Log](https://github.com/xspec/xspec/actions/runs/12010849883/job/33478586460) ends with:
```
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.tar.gz](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.tar.gz)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.tar.gz](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.tar.gz) (136 kB at 475 kB/s)
[INFO] Downloading from xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/maven-metadata.xml](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/maven-metadata.xml)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/maven-metadata.xml](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/maven-metadata.xml)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/maven-metadata.xml](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/maven-metadata.xml) (293 B at 2.0 kB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.zip.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.zip.asc)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.zip.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.zip.asc) (689 B at 15 kB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-javadoc.jar.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-javadoc.jar.asc)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-javadoc.jar.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-javadoc.jar.asc) (689 B at 14 kB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.jar](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.jar)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.jar](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.jar) (186 kB at 1.1 MB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.pom](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.pom)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.pom](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.pom) (8.5 kB at 58 kB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-sources.jar.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-sources.jar.asc)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-sources.jar.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-sources.jar.asc) (689 B at 15 kB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.zip](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.zip)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.zip](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.zip) (219 kB at 1.5 MB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.jar.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.jar.asc)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.jar.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.jar.asc) (689 B at 14 kB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-javadoc.jar](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-javadoc.jar)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-javadoc.jar](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-javadoc.jar) (42 kB at 291 kB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.pom.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.pom.asc)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.pom.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3.pom.asc) (689 B at 14 kB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-sources.jar](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-sources.jar)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-sources.jar](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-sources.jar) (9.2 kB at 65 kB/s)
[INFO] Uploading to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.tar.gz.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.tar.gz.asc)
[INFO] Uploaded to xspec-io.ossrh: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.tar.gz.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1041/io/xspec/xspec/3.1.3/xspec-3.1.3-enduser-files.tar.gz.asc) (689 B at 15 kB/s)
[INFO]  * Upload of locally staged artifacts finished.
[INFO]  * Closing staging repository with ID "ioxspec-1041".
Waiting for operation to complete...
.............
[INFO] Remote staged 1 repositories, finished with success.
[INFO] Remote staging repositories are being released...
Waiting for operation to complete...
........
[INFO] Remote staging repositories released.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:27 min
[INFO] Finished at: 2024-11-25T13:18:20Z
[INFO] ------------------------------------------------------------------------
```

I don't see it in Maven Central yet but will check again later.

**Comment by galtm** [comment]
Now I see 3.1.3 listed in https://central.sonatype.com/artifact/io.xspec/xspec/versions and https://repo.maven.apache.org/maven2/io/xspec/xspec/

**Comment by galtm** [comment]
> 3\. Create a pull request for [the Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support)

I'm going to skip this for now. My PRs https://github.com/xspec/oXygen-XML-editor-xspec-support/pull/56 and https://github.com/xspec/oXygen-XML-editor-xspec-support/pull/57 from April and October 2024, respectively, are still in the queue. Unless someone is actively maintaining that repo, maybe pull requests for the main XSpec releases are good enough.

**Comment by cmarchand** [comment]
Thanks a lot, @galtm !
I'm gonna use this this evening !
