### ISSUE TITLE
Release v1.6.0

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#891]
I'd propose releasing it around 25 April.

* [Project v1.6.0](https://github.com/xspec/xspec/projects/7)

Some of the notable changes on v1.6.0 would be:

* Text Value Templates (expand-text) (#711)
* Code coverage on Saxon-HE (#795)
* Compatible with Saxon 10.0
  * Note: Code Coverage does not work (#852)
* Compatible with Oxygen 22.0

Also I'd propose:

* v1.6.0 is the last version to support Saxon 9.7.
* Bump the next version to v2.0.0.
* In v2.0.0, set `/xsl:stylesheet/@version`=`3.0` in `src/**/*.xsl`.

Note that v2.0.0 does not necessarily mean that fancy features are coming in. Incrementing the major version just reflects the fact that XSpec will no longer work on XSLT 2.0 processors (≒ Saxon 9.7).

I created a [project](https://github.com/xspec/xspec/projects) and a [milestone](https://github.com/xspec/xspec/milestones) for v2.0.0 accordingly.

---
### Copy of [Release Workflow](https://github.com/xspec/xspec/wiki/Release-Workflow)

1. Prepare the release

   - [x] Write release notes (draft)
   - [x] Create a pull request [removing](https://github.com/xspec/xspec/wiki/Release-Workflow#updating-pomxml) `SNAPSHOT` from the version of `pom.xml` and merge it into `master` (#890)

1. Release it
   - [x] [Deploy](https://github.com/xspec/xspec/wiki/Deploy-XSpec-artifact-to-Maven-Central) the XSpec artifact to Maven Central
        * This step must be done immediately before publishing the release so that we can fix any error in `pom.xml` which can be found only by deploying the artifact
   - [x] Publish the release at [Releases](https://github.com/xspec/xspec/releases) page
   - [x] [Promote](https://github.com/xspec/xspec/wiki/Release-Workflow#promoting-the-release) the release

1. Prepare the next development
   - [x] Close the [project](https://github.com/xspec/xspec/projects) and the [milestone](https://github.com/xspec/xspec/milestones) related to the release
   - [x] Create the project and the milestone for the next release

1. Start the next development
   - [x] Create a pull request [incrementing](https://github.com/xspec/xspec/wiki/Release-Workflow#updating-pomxml) the version (with `SNAPSHOT`) of `pom.xml` and merge it into `master` (#902)
   - [x] Create a pull request [updating](https://github.com/xspec/xspec/wiki/Release-Workflow#updating-oxygen-add-on) the Oxygen add-on and merge it into `master` (#914)

**Comment by AirQuick** [comment]
@cirulls 
What do you think?

**Comment by AirQuick** [comment]
@cirulls , @galtm 
Because so far we don't know a release note generator best suited for our convention (#601), I developed my own generator and generated another draft release note in https://github.com/xspec/xspec/releases.
Does it look fine?
* Some pull request types which will not interest end users are collapsed intentionally in `▸ Details`
* Since **Merged Pull Requests** and **Closed Issues** are fully automated, they don't include some issues and links which exist in @cirulls's [draft](https://github.com/xspec/xspec/releases/tag/untagged-acfeb01ab567a2d2a5be).

**Comment by AirQuick** [comment]
> I developed my own generator and generated another draft release note

@xspec/xspec 
This generator requires every merged pull request to have a milestone. To ensure it, I installed [PR Milestone Check](https://github.com/marketplace/pr-milestone-check) in this repository. It requires only minimum permission and seems to be used actively in https://github.com/strimzi/strimzi-kafka-operator/pulls. So I think it's safe.

**Comment by AirQuick** [comment]
* No more changes likely to be made into the master branch.
* Updated the release note [draft](https://github.com/xspec/xspec/releases/tag/untagged-8a623fc963f74b025892) to reflect the recent changes.
* Announced in [Google Groups](https://groups.google.com/d/msg/xspec-users/zdoqR6NOX1g/JR2-ycSTAQAJ).

**Comment by galtm** [comment]
> developed my own generator and generated another draft release note

Thanks for putting this together. The new generated draft is fine. (I'm not sure if most users care about the distinction between "Commented by" and "Reviewed by", but if you prefer the separate columns, that is fine.)

In the highlighted item, "Tested on Saxon 10.0 (Code Coverage does not work #852)", the role of the phrase in parentheses is a little unclear. Tested once with Saxon 10, enough to find out that code coverage doesn't work? Or testing routinely with Saxon 10, and everything works except for code coverage? If the latter, then consider making "Tested on Saxon 10.0" stand on its own as a bulleted item and then add a subbullet like "Note: Code coverage does not work with Saxon 10.0 (#852)".

**Comment by galtm** [comment]
One more thing: I like the collapsed "Details" sections and your choice of what goes there.

**Comment by AirQuick** [comment]
Thanks, @galtm 
I regenerated [the draft release note](https://github.com/xspec/xspec/releases):
* Single **Contributors** column
* Revised **Summary**

**Comment by galtm** [comment]
The summary looks great, and I like the new phrasing, "Compatible with". The single Contributors column is fine. (By the way, I was not opposed to identifying the author of each pull request, as that person probably did a lot more work than the commenters and reviewers.)

**Comment by AirQuick** [comment]
> that person probably did a lot more work than the commenters and reviewers

That makes sense too. I split the column into **Author** and **Participants**.

**Comment by AirQuick** [comment]
I've merged #890. Let's go on to this next step:

> [Deploy](https://github.com/xspec/xspec/wiki/Deploy-XSpec-artifact-to-Maven-Central) the XSpec artifact to Maven Central
> * This step must be done immediately before publishing the release so that we can fix any error in `pom.xml` which can be found only by deploying the artifact

@cmarchand 
Can you please deploy the v1.6.0 artifact (== the current master) to Maven Central at your convenience?
(Looks like @cirulls is busy nowadays. I don't have any expertise nor an account for these Maven things.)

**Comment by cmarchand** [comment]
[Done](https://repo1.maven.org/maven2/io/xspec/xspec/1.6.0/). 
I have also  created a tag, and changed pom version to 1.6.1-SNAPSHOT to avoid re-creating the 1.6.0.
Sorry for the delay, I was OFF two days.

**Comment by AirQuick** [comment]
Thanks, @cmarchand 
Let me reopen this issue for finishing the rest of the tasks.

**Comment by AirQuick** [comment]
> changed pom version to 1.6.1-SNAPSHOT to avoid re-creating the 1.6.0.

Changed where? The same goal will be achieved by #902, perhaps?

**Comment by cmarchand** [comment]
I wasn't able to push pom modifications commit.

**Comment by AirQuick** [comment]
> I wasn't able to push pom modifications commit.

Directly to the `master` branch?
The master branch is protected by a GitHub branch protection rule. You always need to go through a pull request.

**Comment by AirQuick** [comment]
>    * [x]  Publish the release at [Releases](https://github.com/xspec/xspec/releases) page

[Done](https://github.com/xspec/xspec/releases/tag/v1.6.0)

>    * [ ]  [Promote](https://github.com/xspec/xspec/wiki/Release-Workflow#promoting-the-release) the release

@cmarchand and @yamahito
You can tweet it :)

**Comment by cmarchand** [comment]
Done !

**Comment by AirQuick** [comment]
The release workflow completed. Thanks everyone.

**Comment by AirQuick** [comment]
@xspec/oxygen-xml-editor-xspec-support
A wrap-up of XSpec v1.6.0 in view of Oxygen plugin:
* You can override `mode="x:generate-id"` instead of patching the stylesheet directly. (#734)
* The originating .xspec file URI is available by default in the report XML. (#735) 
* The scenario ID is readily available in the result XML (#770), although you will still need to generate the ID by yourself using #734

**Comment by cirulls** [comment]
> Looks like @cirulls is busy nowadays.
@AirQuick, @galtm, @cmarchand: Congratulations for releasing XSpec v1.6.0! I'm really sorry for missing this release and being silent, I started a new job and have been quite busy with other things. I'm catching up on the XSpec emails and notifications of the past months, I'll try to be more responsive in the upcoming weeks.

Well done again on XSpec v1.6.0!

**Comment by AirQuick** [comment]
@cirulls 
We were waiting for you 😃 
Now I'm inclined to resolve #932 so that any one of the @xspec/xspec members can push things forward even if all the other ones are busy.

**Comment by vincentml** [comment]
Congratulations on the new job @cirulls !

**Comment by cirulls** [comment]
Thanks all for your kind words and sorry again for the long silence.

@AirQuick: it's a great idea to automate the maven deployment, this will also speed up the release phase and make it less dependant on individuals being available. I'll comment directly on the issue.

**Comment by AlexJitianu** [comment]
Thank you again for the enhancements in the XSLTs with regards to @xspec/oxygen-xml-editor-xspec-support. Upgrading to XSpec 1.6.0 was a breeze! Porting those XSLT patches was always a bit of a challenge!

**Comment by AirQuick** [comment]
Glad to hear that, and thanks for keeping the cool plugin updated, @AlexJitianu 

In the next version, `v2.0`, I'm thinking to support "[the user requested some specific scenarios to be run](https://github.com/xspec/oXygen-XML-editor-xspec-support/blob/63615954126b7791a849f9bfb632cd5a8470d4fa/frameworks/xspec/oxygen-results-view/build_report.xml#L95-L101)" by default but in a different way (using `@focus` internally), not only because the feature would be useful but also because the way **Oxygen XSpec Helper View** currently does seems incompatible with [`x:variable`](https://github.com/xspec/xspec/wiki/Writing-Scenarios#xspec-variables).
